### ISSUE TITLE
Too many login attempts

### ISSUE THREAD

**Issue by svenmueller** [docker/dockercloud-haproxy#33] opened 2016-04-13 19:37 UTC
We run haproxy in Docker Cloud using a stackfile. The log always shows the following problem which leads to a locked Docker account sooner or later:

```
2016-04-13T13:16:00.784169614Z INFO:haproxy:Websocket open
2016-04-13T13:16:01.060468731Z ERROR:haproxy:Status 429 (GET https://cloud.docker.com/api/app/v1/container/84995beb-f414-4411-a418-55ed286772f4/). Response: {"detail": "Too many login attempts."}
2016-04-13T13:16:01.060514990Z 
2016-04-13T13:16:11.294212262Z ERROR:haproxy:Status 429 (GET https://cloud.docker.com/api/app/v1/container/84995beb-f414-4411-a418-55ed286772f4/). Response: {"detail": "Too many login attempts."}
2016-04-13T13:16:11.294255913Z 
2016-04-13T13:16:21.514026149Z ERROR:haproxy:Status 429 (GET https://cloud.docker.com/api/app/v1/container/84995beb-f414-4411-a418-55ed286772f4/). Response: {"detail": "Too many login attempts."}
2016-04-13T13:16:21.514074063Z 
```

What could be the reason for this error? Configuration issue?

Thx,
Sven

**Comment by tifayuki** [comment] 2016-04-15 11:12
@svenmueller 

That means you have too many login attempts with wrong credentials. It could be caused by you leave some containers running on a node has been removed from the dockercloud.

Please open a ticket to the support and ask them to unlock you account.

**Comment by svenmueller** [comment] 2016-04-15 11:26
@tifayuki as you can see in the logs the this is triggered by haproxy container itself when running in Docker cloud (using stackfile). The question is why this happens.

**Comment by svenmueller** [comment] 2016-04-15 11:27
Same problem is reported here: #29

**Comment by tifayuki** [comment] 2016-04-15 13:18
@svenmueller 
As I said, when API call returns 429, it means your account is blocked for a security reason. This is usually because of too many requests(logins, api calls, etc.) with an invalid credentials. To know the exact reason that causes the account lock, you need to the docker support team.

**Comment by tifayuki** [comment] 2016-04-28 17:17
This is related to API throttling, and we are keep optimizing it on the server side.
Not really an error of this haproxy image, and I am going to close this issue at the moment.
If you still have such a problem, please contact support@docker

**Closed by tifayuki** 2016-04-28 17:17 UTC

**Comment by svenmueller** [comment] 2016-04-28 17:42
@tifayuki contacting the Docker support resulted in no answer. And yes we still see this issue. I would like to re-open this issue.

**Comment by tifayuki** [comment] 2016-04-28 18:05
@svenmueller 
There is a PR(https://github.com/docker/dockercloud-haproxy/tree/prevent_retrying_on_401) that does not retry the API request when receiving a 401 error. This can mitigate the chance of locking your account, when the API key becomes invalid. The changes will also apply to all our system containers. Hope this can be helpful.

**Comment by evanp** [comment] 2016-04-29 18:18
@tifayuki that sounds great. I've only seen this problem on BYON nodes on Docker Cloud, by the way.
