### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by jake-low** [docker/dockercloud-haproxy#97] opened 2016-08-01 07:26 UTC
Perplexed by this; it's a very minimal config. Running in Docker Cloud

stack "edge":

```
proxy:
  image: dockercloud/haproxy
  links:
    - webserver.foo-dot-com:foo
    - webserver.bar-dot-com:bar
  ports:
    - 80:80
  roles:
    - global
```

stack "foo-dot-com"

```
webserver:
  image: # an image I wrote; listens on 80
  environment:
    - VIRTUAL_HOST=foo.example.com # "foo" subdomain on a domain I own
```

stack "bar-dot-com":

```
webserver:
  image: # another image I wrote; listens on 80
  environment:
    - VIRTUAL_HOST=bar.example.com # "bar" subdomain on a domain I own
```

`dig` shows that the CNAME entries for `foo.example.com` and `bar.example.com` point to `proxy.edge.<hash>.svc.dockerapp.io`.

`docker-cloud exec foo curl localhost` works, and same for bar.

`docker-cloud exec proxy curl foo` works, and also for bar.

Clearly, the backend containers are working.

I read the instructions carefully and I don't _think_ I'm misconfiguring.

There's nothing (apart from the config output) in the HAProxy logs, even when I add `EXTRA_GLOBAL_SETTINGS=debug`. The only hint that something goes wrong is that `Errors/Conn` increments in the statistics report page every time I `curl foo.example.com` from my machine.

And, of course, finally, `curl foo.example.com` returns `503 Service Unavailable`.

**Comment by Starefossen** [comment] 2016-08-01 08:19
Possible duplicate of https://github.com/docker/dockercloud-haproxy/issues/4

**Comment by tifayuki** [comment] 2016-08-01 09:16
Cannot reproduce the issue, and the log shows it is working as expected:

```
proxy-1 | 2016-08-01T09:10:25.754232522Z INFO:haproxy:dockercloud/haproxy 1.5.3 has access to the Docker Cloud API - will reload list of backends in real-time
proxy-1 | 2016-08-01T09:10:25.754837866Z INFO:haproxy:dockercloud/haproxy PID: 5
proxy-1 | 2016-08-01T09:10:25.991805212Z INFO:haproxy:==========BEGIN==========
proxy-1 | 2016-08-01T09:10:25.992129676Z INFO:haproxy:Websocket open
proxy-1 | 2016-08-01T09:10:26.660767704Z INFO:haproxy:Linked service: BAR(fc276639-6360-4edc-9fdd-3fa86d51fe5f), FOO(926fc494-ecc9-43e9-9082-0f61c2b0725a)
proxy-1 | 2016-08-01T09:10:26.661149632Z INFO:haproxy:Linked container: BAR_1(520a9624-cae6-47c9-8db3-94e60e9e3a52), FOO_1(cccb3e91-3383-4091-9dd2-06fafc8e7c98)
proxy-1 | 2016-08-01T09:10:26.662751733Z INFO:haproxy:HAProxy configuration:
proxy-1 | 2016-08-01T09:10:26.662770941Z global
proxy-1 | 2016-08-01T09:10:26.662793788Z   log 127.0.0.1 local0
proxy-1 | 2016-08-01T09:10:26.662800976Z   log 127.0.0.1 local1 notice
proxy-1 | 2016-08-01T09:10:26.662807705Z   log-send-hostname
proxy-1 | 2016-08-01T09:10:26.662813935Z   maxconn 4096
proxy-1 | 2016-08-01T09:10:26.662820061Z   pidfile /var/run/haproxy.pid
proxy-1 | 2016-08-01T09:10:26.662833835Z   user haproxy
proxy-1 | 2016-08-01T09:10:26.662841331Z   group haproxy
proxy-1 | 2016-08-01T09:10:26.662847513Z   daemon
proxy-1 | 2016-08-01T09:10:26.662854206Z   stats socket /var/run/haproxy.stats level admin
proxy-1 | 2016-08-01T09:10:26.662860516Z   ssl-default-bind-options no-sslv3
proxy-1 | 2016-08-01T09:10:26.662867830Z   ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA
proxy-1 | 2016-08-01T09:10:26.662879350Z   debug
proxy-1 | 2016-08-01T09:10:26.662885460Z defaults
proxy-1 | 2016-08-01T09:10:26.662891545Z   balance roundrobin
proxy-1 | 2016-08-01T09:10:26.662897576Z   log global
proxy-1 | 2016-08-01T09:10:26.662903591Z   mode http
proxy-1 | 2016-08-01T09:10:26.662909578Z   option redispatch
proxy-1 | 2016-08-01T09:10:26.662915513Z   option httplog
proxy-1 | 2016-08-01T09:10:26.662921451Z   option dontlognull
proxy-1 | 2016-08-01T09:10:26.662927331Z   option forwardfor
proxy-1 | 2016-08-01T09:10:26.662933152Z   timeout connect 5000
proxy-1 | 2016-08-01T09:10:26.662941323Z   timeout client 50000
proxy-1 | 2016-08-01T09:10:26.662951258Z   timeout server 50000
proxy-1 | 2016-08-01T09:10:26.662957400Z listen stats
proxy-1 | 2016-08-01T09:10:26.662963455Z   bind :1936
proxy-1 | 2016-08-01T09:10:26.662969320Z   mode http
proxy-1 | 2016-08-01T09:10:26.662975303Z   stats enable
proxy-1 | 2016-08-01T09:10:26.662981053Z   timeout connect 10s
proxy-1 | 2016-08-01T09:10:26.662990207Z   timeout client 1m
proxy-1 | 2016-08-01T09:10:26.662996220Z   timeout server 1m
proxy-1 | 2016-08-01T09:10:26.663020392Z   stats hide-version
proxy-1 | 2016-08-01T09:10:26.663027513Z   stats realm Haproxy\ Statistics
proxy-1 | 2016-08-01T09:10:26.663033732Z   stats uri /
proxy-1 | 2016-08-01T09:10:26.663039613Z   stats auth stats:stats
proxy-1 | 2016-08-01T09:10:26.663045450Z frontend port_80
proxy-1 | 2016-08-01T09:10:26.663051250Z   bind :80
proxy-1 | 2016-08-01T09:10:26.663058665Z   reqadd X-Forwarded-Proto:\ http
proxy-1 | 2016-08-01T09:10:26.663065518Z   maxconn 4096
proxy-1 | 2016-08-01T09:10:26.663071440Z   acl is_websocket hdr(Upgrade) -i WebSocket
proxy-1 | 2016-08-01T09:10:26.663077513Z   acl host_rule_1 hdr(host) -i foo.example.com
proxy-1 | 2016-08-01T09:10:26.663083525Z   acl host_rule_1_port hdr(host) -i foo.example.com:80
proxy-1 | 2016-08-01T09:10:26.663089527Z   use_backend SERVICE_FOO if host_rule_1 or host_rule_1_port
proxy-1 | 2016-08-01T09:10:26.663095458Z   acl host_rule_2 hdr(host) -i bar.example.com
proxy-1 | 2016-08-01T09:10:26.663101375Z   acl host_rule_2_port hdr(host) -i bar.example.com:80
proxy-1 | 2016-08-01T09:10:26.663107240Z   use_backend SERVICE_BAR if host_rule_2 or host_rule_2_port
proxy-1 | 2016-08-01T09:10:26.663113308Z backend SERVICE_BAR
proxy-1 | 2016-08-01T09:10:26.663119058Z   server BAR_1 10.7.0.3:80 check inter 2000 rise 2 fall 3
proxy-1 | 2016-08-01T09:10:26.663124992Z backend SERVICE_FOO
proxy-1 | 2016-08-01T09:10:26.663130762Z   server FOO_1 10.7.0.2:80 check inter 2000 rise 2 fall 3
proxy-1 | 2016-08-01T09:10:26.663587508Z INFO:haproxy:Launching HAProxy
proxy-1 | 2016-08-01T09:10:26.668697481Z INFO:haproxy:HAProxy has been launched(PID: 13)
proxy-1 | 2016-08-01T09:10:26.668994672Z INFO:haproxy:===========END===========
proxy-1 | 2016-08-01T09:10:26.674696111Z Available polling systems :
proxy-1 | 2016-08-01T09:10:26.674912858Z       epoll : pref=300,  test result OK
proxy-1 | 2016-08-01T09:10:26.675034483Z        poll : pref=200,  test result OK
proxy-1 | 2016-08-01T09:10:26.675138373Z      select : pref=150,  test result FAILED
proxy-1 | 2016-08-01T09:10:26.675185542Z Total: 3 (2 usable), will use epoll.
proxy-1 | 2016-08-01T09:10:26.675330517Z Using epoll() as the polling mechanism.
proxy-1 | 2016-08-01T09:12:06.367846424Z 00000000:port_80.accept(000a)=000b from [193.153.99.77:60182]
proxy-1 | 2016-08-01T09:12:06.368186791Z 00000000:port_80.clireq[000b:ffffffff]: GET / HTTP/1.1
proxy-1 | 2016-08-01T09:12:06.368281561Z 00000000:port_80.clihdr[000b:ffffffff]: host:bar.example.com
proxy-1 | 2016-08-01T09:12:06.368322571Z 00000000:port_80.clihdr[000b:ffffffff]: User-Agent: curl/7.43.0
proxy-1 | 2016-08-01T09:12:06.368382905Z 00000000:port_80.clihdr[000b:ffffffff]: Accept: */*
proxy-1 | 2016-08-01T09:12:06.371534699Z 00000000:SERVICE_BAR.srvrep[000b:000c]: HTTP/1.1 200 OK
proxy-1 | 2016-08-01T09:12:06.371619369Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: Server: nginx/1.10.1
proxy-1 | 2016-08-01T09:12:06.371771048Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: Date: Mon, 01 Aug 2016 09:12:06 GMT
proxy-1 | 2016-08-01T09:12:06.371866794Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: Content-Type: text/html; charset=UTF-8
proxy-1 | 2016-08-01T09:12:06.371928998Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: Transfer-Encoding: chunked
proxy-1 | 2016-08-01T09:12:06.371966073Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: Connection: keep-alive
proxy-1 | 2016-08-01T09:12:06.372023508Z 00000000:SERVICE_BAR.srvhdr[000b:000c]: X-Powered-By: PHP/5.6.23
proxy-1 | 2016-08-01T09:12:06.488875519Z 00000001:port_80.clicls[000b:000c]
proxy-1 | 2016-08-01T09:12:06.489010497Z 00000001:port_80.closed[000b:000c]
proxy-1 | 2016-08-01T09:12:25.243197855Z 00000002:port_80.accept(000a)=000b from [193.153.99.77:60192]
proxy-1 | 2016-08-01T09:12:25.243868002Z 00000002:port_80.clireq[000b:ffffffff]: GET / HTTP/1.1
proxy-1 | 2016-08-01T09:12:25.243952231Z 00000002:port_80.clihdr[000b:ffffffff]: host:foo.example.com
proxy-1 | 2016-08-01T09:12:25.244164999Z 00000002:port_80.clihdr[000b:ffffffff]: User-Agent: curl/7.43.0
proxy-1 | 2016-08-01T09:12:25.244321714Z 00000002:port_80.clihdr[000b:ffffffff]: Accept: */*
proxy-1 | 2016-08-01T09:12:25.247553472Z 00000002:SERVICE_FOO.srvrep[000b:000c]: HTTP/1.1 200 OK
proxy-1 | 2016-08-01T09:12:25.247773377Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: Server: nginx/1.10.1
proxy-1 | 2016-08-01T09:12:25.248142764Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: Date: Mon, 01 Aug 2016 09:12:25 GMT
proxy-1 | 2016-08-01T09:12:25.248359954Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: Content-Type: text/html; charset=UTF-8
proxy-1 | 2016-08-01T09:12:25.248573400Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: Transfer-Encoding: chunked
proxy-1 | 2016-08-01T09:12:25.248738942Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: Connection: keep-alive
proxy-1 | 2016-08-01T09:12:25.249077411Z 00000002:SERVICE_FOO.srvhdr[000b:000c]: X-Powered-By: PHP/5.6.23
proxy-1 | 2016-08-01T09:12:25.369217664Z 00000003:port_80.clicls[000b:000c]
proxy-1 | 2016-08-01T09:12:25.369678999Z 00000003:port_80.closed[000b:000c]
```

I guess it is related to the network issue.

**Comment by jake-low** [comment] 2016-08-01 19:24
All the stacks are deployed on a single DigitalOcean droplet. If you want to know anything about the network config, tell me what to run and I'll post the output.

Also, FWIW it takes less than a second to redeploy any of the stacks (wrt. the comment in #4 about the redeploy being "too fast" for HAProxy).

**Comment by cosmostail** [comment] 2016-08-02 17:51
happens with the VIRTUAL_HOST configuration. You can reproduce it right after you added that options. 

Before adding VIRTUAL_HOST, everything works as expected.

**Comment by Dids** [comment] 2016-08-10 10:03
@cosmostail That didn't help here. In my case, every few redeployments end up in 503, and all I can do is restart/redeploy the HAProxy container.

**Comment by koszta** [comment] 2016-08-15 09:51
Same error here, it could be a result of no events received from docker cloud, so the proxy will not be reconfigured, only restart/redeploy helps.

In the logs, I found these multiple times:
```
INFO:haproxy:Auth error: Not Authorized, retry in 1 hour
```

I guess docker cloud changed the API keys, after restarting the container, it works again, no authorization errors anymore.

**Comment by maxfrigge** [comment] 2016-08-23 10:31
Same issue here. I have also seen haproxy picking up the changes after a couple of minutes, but it shouldn't take longer then redeploying haproxy to make this a useful feature.

**Comment by Dids** [comment] 2016-08-27 08:55
After redeploying a container, HAProxy stopped working for that particular virtualhost, threw the 503 and then I saw this in the logs:

```
ContainerStarted: unable to register 589216fe8082a7329f14f9fc20723f33dea7da00e8e4fb0991c139edd6737122 with weaveDNS: 404 Not Found: 404 page not found
```

**Comment by tifayuki** [comment] 2016-09-05 04:23
@Dids 
The 503 issue after the redeployment comes from the weave network we are using. As I tested locally, weave 1.5.2 (the version we are using) has a 20-30 seconds delay, resulting in 20-30 seconds 503 down time. The latest version 1.6 doesn't have such a problem. We are currently testing the new weave version, and will make a new release as soon as possible.

**Comment by tifayuki** [comment] 2016-09-05 05:14
@koszta 

It means the token assigned to the haproxy container is revoked, which usually doesn't happen. As I recalled like 20 days ago, there is a server error causing a few containers' key become invalid.  I added some logic to prevent a container with an invalid key from flooding to our API. That's why you see the error message in the log. This error can be fixed simply by redeploy the service. 

The next time when you see this error, please contact our support team, so that we can identify where the problem is. 

Thank you.

**Comment by tifayuki** [comment] 2016-09-28 14:25
we have upgraded the weave to 1.6, which should mitigate the 503 issue:
https://forums.docker.com/t/docker-cloud-release-notes-09-27-2016/22655

**Comment by keyscores** [comment] 2016-10-24 18:11
@tifayuki 
I was testing HA proxy on digital ocean, and it worked great. Then I decided to test an HAproxy instance on Packet, which fails. I don't get a response when requesting the endpoint or IP. 
Inspecting the logs come up with: 
> INFO:haproxy:Auth error: Not Authorized, retry in 1 hour

Redeploying does not work.

No configs were changed in the stack. I simply replaced the nodes from digitalocean to packet.

**Comment by tifayuki** [comment] 2016-10-24 18:38
@keyscores 

Looks like the auth token is not valid any more. Docker Cloud assign a new token every time when a service is redeployed. It could be like something is wrong on the server side.
Can you open a support ticket so that our engineer can check which part goes wrong?

Thank you.

**Comment by keyscores** [comment] 2016-10-25 18:04
@tifayuki Yes I already have opened a request, but I have no answer. Can you check?

What token is this? Do I have control over it?

**Comment by tifayuki** [comment] 2016-10-25 18:45
@keyscores 
If you exec into the haproxy container and do `env`, there should be one environment like `DOCKERCLOUD_AUTH=TutumAccessKey 2cxxxxxxxx40`, which allows you to talk to tutum api. For example, `curl -H "Authorization: TutumAccessKey 2cxxxxxxxx40" https://cloud.docker.com/api/tutum/v1/auth/`. 

Can you try the same command to see if the key is valid?

And, if you redeploy the service, in the new container, the key will be assigned with a new one. If that key doesn't work either, we have to look into your account to see if something goes wrong.

Let me know what is the situation on your side.

Thank you.

**Closed** 2017-03-07 23:55 UTC
